### ISSUE TITLE
update the name of entry

### ISSUE THREAD

**Issue by Nshrtaegraegr** [peshay/tpmstore#8]
is it possible to update the name of an entry, it looks like the primary key

**Comment by peshay** [comment]
I plan to implement the following functionalities:
```
        search:
            description:
                - Searchtstring to use for the TeamPasswordManager search.
            required: If 'name' is not set.
            default: 'name:[name]'
        name:
            description:
                - Name of the entry in TeamPasswordManager. Will search for exact match.
            required: If 'search' is not set.
        return_value:
            description:
                - Which fields from found entries should be returned.
            required: False
            default: password
```
therefore you could update an entry like this:
```
{{ lookup('tpmstore', tpmurl, tpmuser, tpmpass, 'name=New entry name', 'search=name:[Old entry name]' 'create=True', 'password=random') }}
```
Or to get the project_id
```
{{ lookup('tpmstore', tpmurl, tpmuser, tpmpass, 'return_value=project_id', 'search=name:[some entry name]' 'create=True', 'password=random') }}
```
